[phases.setup]
nixPkgs = ['nodejs-16_x', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['export NODE_OPTIONS=--openssl-legacy-provider && ng build --prod']

[start]
cmd = "npm start"

[variables]
NODE_OPTIONS = "--openssl-legacy-provider"
